name: code-checks

on:
  pull_request: {}
  push:
    branches:
      - "**"

jobs:
  gosec:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@0.40.0
    with:
      install-go: true
      go-version: "1.22.1"
      lint-commands: |
        make bootstrap-tools
        make lintsec

  golint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@0.40.0
    with:
      install-go: true
      go-version: "1.22.1"
      lint-commands: |
        make bootstrap-tools
        make lint
