name: create-default-labels
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
  workflow_dispatch: {}

jobs:
  size-label:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-create-default-labels.yml@0.41.2
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

