name: update-snyk

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  update-snyk:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-scan-snyk.yml@0.14.1
    with:
      install-go: true
      go-version: '1.18.1'
      scan-commands: snyk monitor
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}
